### PR TITLE
fix some problem

### PR DESCRIPTION
**Pull request by raindylong**
fix some problem when the size is too large from upstream DNS server

### CODE REVIEW

**Comment by kenshinx** [comment]
I do not quite understand why you need set the `UDPSize ` parameter, as the DNS protocol [RFC 1035](https://www.ietf.org/rfc/rfc1035.txt) , DNS messages should be 512 octets or less. Please paste more details let us known adjust the UDPSize is make sense. Furthermore, i think hardcode `4096` is not a good idea, if we really need set `UDPSize`, may be we should consider put it into config file.

kenshin

**Comment by raindylong** [comment]
@kenshinx, in my case, I got some errors like that:

> 2017/02/07 17:24:40 [INFO] 10.80.1.185 lookup　web.houyi.baofeng.net IN A
2017/02/07 17:24:40 [DEBUG] web.houyi.baofeng.net didn't found in hosts file
2017/02/07 17:24:40 [DEBUG] web.houyi.baofeng.net IN A didn't hit cache
2017/02/07 17:24:40 [WARN] web.houyi.baofeng.net. socket error on 10.17.0.1:53
2017/02/07 17:24:40 [WARN] error:dns: buffer size too small

I check the response package from 10.17.0.1:53(the upstream DNS server), it has "AUTHORITY SECTION" & "ADDITIONAL SECTION" (not only "ANSWER SECTION"), it's large than 512, so I set the UDPSize to fix this problem.
Yes, I think put the setting in the config file is the better way.

**Comment by kenshinx** [comment]
@raindylong , as you said, do you mind tuning your PR and put the `UDPSize` setting in the configuration file? Thanks

**Comment by kenshinx** [comment]
I think use Extension Mechanisms for DNS(EDNS(0)) to support larger response packets are better choice.

**Pull request closed without merging**
