### PR TITLE
Domain specific DNS server 

### PR DESCRIPTION
**Pull request by bigeagle**
This PR contains 4 changes:
1. Add domain specific DNS server support
2. Specify DNS server in `server-list-file` in addition to `resolv.conf` in order to add `port` option
3. Add option to disable redis cache
4. Only cache successful responses

I found you developed this project for servers, maybe these features are not needed and may introduce uncertainty. It's OK for me to maintain a fork for personal use. :)

Cheers,

### CODE REVIEW

**Comment by kenshinx** [comment]
Can you please send the PR individual?
As you mentioned this project is for server scenario. So i can decide which PR can be merge into trunk which should be self-contained in your branch.

**Comment by bigeagle** [comment]
Maybe it's better to decide which features is useful, so that I can send another PR?

**Comment by kenshinx** [comment]
3.Add option to disable redis cache
4.Only cache successful responses
No doubt about that. Above two features can be merged into master easily.
But `dnsmasq style domain specific server supported` i am not very sure is this should be merged now.

**Comment by bigeagle** [comment]
OK, I'll send you another PR later this week. : )

**Comment by kenshinx** [comment]
Cool. :s

**Comment by kenshinx** [comment]
Features has been merged in another PR.
This can be closed.

**Pull request merged**
